### ISSUE TITLE
how do you configure the spk.f0 file in which min and max f0 value was written

### ISSUE THREAD

**Issue by coderwhisky** [unilight/cdvae-vc#4]
I get a custom speaker, and set minf0=30 maxf0=450 manually , then train the model. but i got unexpected convert result : SM3 convert to custom speaker still listens like SM3's voice , custom speaker convert to TF1 got silence.
so ,can you give some hint about your way to generate spk.f0 file under conf directory

**Comment by unilight** [comment]
Hi @wesky260643 ,

Let me confirm a few points.
1. It sounds that there is a posterior collapse problem.  Could you check if the KLD during training goes almost 0?
2. Did you set minf0 and max f0 following the suggestion in issue #3 ?
3. Did you train the custom speaker with, for example, the 12 speakers in the VCC2018 dataset?

**Comment by coderwhisky** [comment]
> Hi @wesky260643 ,
> 
> Let me confirm a few points.
> 
> 1. It sounds that there is a posterior collapse problem.  Could you check if the KLD during training goes almost 0?
> 2. Did you set minf0 and max f0 following the suggestion in issue #3 ?
> 3. Did you train the custom speaker with, for example, the 12 speakers in the VCC2018 dataset?

apply to 1: KLD averages to about 360-380 finally 
apply to 2: I fix my min/max f0 problem according to #3 
apply to 3: my custom speaker comes from cartoon character

**Comment by unilight** [comment]
@wesky260643 Thank you for the reply.
360-380 is a bit too low. I usually get around 660-740. We may need to further investigate what happened. Also, if the custom speaker (in your case, a cartoon character) is too different from other speakers, posterior collapse might very possibly happen. Let me confirm a few points.
1. Which model did you use?
2. Did you train your model using only the custom speaker or with the VCC2018 dataset?

**Comment by coderwhisky** [comment]
@unilight thanks for your reply
1. I use the cdvae-cls-gan model
2. I use VCC2018 dataset and three custom speaker
I got my convert result after i fix the min/max f0 problem, the custom speaker's silence problem remain unsolved

**Comment by unilight** [comment]
I see. Does the silence problem only happen when converting from the custom speaker to TF1? Can you try to convert to some other speakers? Or, try to reconstruct the custom speaker? Also, can you convert another speaker to TF1?

**Comment by coderwhisky** [comment]
I fixed my problem. I resample the custom speaker's wav data by librosa , which save data using numpy float , and scipy.io is used in this repo, which save and load data using int16

**Comment by unilight** [comment]
Okay! Good to hear that :)

Closing this issue.
